version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /provider/file
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /provider/pflag
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /provider/appconfig
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      aws-sdk-go:
        patterns:
          - github.com/aws/aws-sdk-go-v2*
          - github.com/aws/smithy-go

  - package-ecosystem: gomod
    directory: /provider/s3
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      aws-sdk-go:
        patterns:
          - github.com/aws/aws-sdk-go-v2*
          - github.com/aws/smithy-go

  - package-ecosystem: gomod
    directory: /provider/azappconfig
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      azure-sdk-for-go:
        patterns:
          - github.com/Azure/azure-sdk-for-go/sdk/*
          - github.com/aws/smithy-go

  - package-ecosystem: gomod
    directory: /provider/azblob
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      azure-sdk-for-go:
        patterns:
          - github.com/Azure/azure-sdk-for-go/sdk/*
          - github.com/aws/smithy-go

  - package-ecosystem: gomod
    directory: /provider/secretmanager
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      cloud.google.com/go:
        patterns:
          - cloud.google.com/go/*
          - google.golang.org/api
          - google.golang.org/grpc
          - google.golang.org/protobuf

  - package-ecosystem: gomod
    directory: /provider/gcs
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      cloud.google.com/go:
        patterns:
          - cloud.google.com/go/*
          - google.golang.org/api

  - package-ecosystem: gomod
    directory: /examples/aws
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      github.com/nil-go/konf:
        patterns:
          - github.com/nil-go/konf*

  - package-ecosystem: gomod
    directory: /examples/azure
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      github.com/nil-go/konf:
        patterns:
          - github.com/nil-go/konf*

  - package-ecosystem: gomod
    directory: /examples/gcp
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      github.com/nil-go/konf:
        patterns:
          - github.com/nil-go/konf*

  - package-ecosystem: github-actions
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
